classdef ProcessingReport < handle
    % PROCESSINGREPORT Generate processing pipeline reports (Markdown)
    %
    % Usage:
    %   report = narwc.reports.ProcessingReport(tracker, survey_id);
    %   report.generate('report.md');

    % NOTE: only used by test_reports
    
    properties (Access = private)
        tracker
        survey_id
        stats
    end
    
    methods
        function obj = ProcessingReport(tracker, survey_id)
            % PROCESSINGREPORT Constructor
            
            obj.tracker = tracker;
            
            if nargin > 1
                obj.survey_id = survey_id;
            else
                obj.survey_id = 'Unknown';
            end
            
            obj.stats = obj.tracker.getSummary();
        end
        
        function generate(obj, output_file, options)
            % GENERATE Generate processing report
            %
            % Inputs:
            %   output_file - Output file path (.md)
            %   options - Name-value pairs:
            %       'IncludeDetails' - Show all changes (default: true)
            %       'MaxDetailsPerStep' - Max changes to show per step (default: 50)
            
            arguments
                obj
                output_file char
                options.IncludeDetails logical = true
                options.MaxDetailsPerStep double = 50
            end
            
            % Create output directory
            output_dir = fileparts(output_file);
            if ~isempty(output_dir) && ~exist(output_dir, 'dir')
                mkdir(output_dir);
            end
            
            % Generate markdown
            content = obj.generateMarkdown(options.IncludeDetails, options.MaxDetailsPerStep);
            
            % Write to file
            fid = fopen(output_file, 'w');
            fprintf(fid, '%s', content);
            fclose(fid);
            
            fprintf('Processing report generated: %s\n', output_file);
        end
        
        function md = generateMarkdown(obj, include_details, max_per_step)
            % GENERATEMARKDOWN Generate markdown report
            
            md = sprintf('# Processing Report\n\n');
            md = [md sprintf('**Survey:** %s  \n', obj.survey_id)];
            md = [md sprintf('**Generated:** %s  \n\n', char(datetime('now')))];
            md = [md sprintf('---\n\n')];
            
            % Summary
            md = [md sprintf('## Summary\n\n')];
            md = [md sprintf('Total changes made: **%d**\n\n', obj.stats.total_changes)];
            
            if obj.stats.total_changes == 0
                md = [md sprintf('No processing changes were made to this survey.\n\n')];
                return;
            end
            
            % Changes by step
            md = [md sprintf('## Changes by Processing Step\n\n')];
            
            if isempty(fieldnames(obj.stats.by_step))
                md = [md sprintf('No steps recorded.\n\n')];
            else
                md = [md sprintf('| Step | Rows Affected |\n')];
                md = [md sprintf('|------|---------------|\n')];
                
                steps = keys(obj.stats.by_step);
                for i = 1:length(steps)
                    step = steps{i};
                    count = obj.stats.by_step(step);
                    md = [md sprintf('| %s | %d |\n', strrep(step, '_', ' '), count)];
                end
                md = [md sprintf('\n')];
            end
            
            % Detailed changes
            if include_details && obj.stats.total_changes > 0
                md = [md obj.generateDetailedChanges(max_per_step)];
            end
            
            md = [md sprintf('---\n\n')];
            md = [md sprintf('*Report generated by NARWC Processing Pipeline*\n')];
        end
        
        function md = generateDetailedChanges(obj, max_per_step)
            % GENERATEDETAILEDCHANGES Generate detailed change log
            
            md = sprintf('## Detailed Changes\n\n');
            
            changes = obj.tracker.getChanges();
            steps = unique({changes.step});
            
            for i = 1:length(steps)
                step = steps{i};
                step_changes = changes(strcmp({changes.step}, step));
                
                md = [md sprintf('### %s (%d changes)\n\n', strrep(step, '_', ' '), length(step_changes))];
                
                % Show changes up to max
                max_show = min(max_per_step, length(step_changes));
                
                for j = 1:max_show
                    change = step_changes(j);
                    md = [md obj.formatChange(change)];
                end
                
                if length(step_changes) > max_show
                    md = [md sprintf('\n*... and %d more changes not shown*\n', ...
                        length(step_changes) - max_show)];
                end
                
                md = [md sprintf('\n')];
            end
        end
        
        function str = formatChange(obj, change)
            % FORMATCHANGE Format a single change for display
            
            rows_str = obj.formatRows(change.row);
            
            if ~isempty(change.description)
                str = sprintf('- **Row(s) %s:** %s\n', rows_str, change.description);
            elseif ~isempty(change.field)
                if ~isempty(change.old_value) && ~isempty(change.new_value)
                    str = sprintf('- **Row(s) %s:** Changed `%s` from `%s` to `%s`\n', ...
                        rows_str, change.field, ...
                        obj.valueToString(change.old_value), ...
                        obj.valueToString(change.new_value));
                else
                    str = sprintf('- **Row(s) %s:** Modified `%s`\n', rows_str, change.field);
                end
            else
                str = sprintf('- **Row(s) %s:** Change recorded\n', rows_str);
            end
        end
        
        function str = formatRows(obj, rows)
            % FORMATROWS Format row numbers for display
            
            if length(rows) == 1
                str = num2str(rows);
            elseif length(rows) <= 5
                str = sprintf('%s', strjoin(arrayfun(@num2str, rows, 'UniformOutput', false), ', '));
            else
                str = sprintf('%d-%d (%d rows)', min(rows), max(rows), length(rows));
            end
        end
        
        function str = valueToString(obj, value)
            % VALUETOSTRING Convert value to string for display
            
            if isempty(value)
                str = '<empty>';
            elseif ismissing(value)
                str = '<missing>';
            elseif isnumeric(value) && isscalar(value)
                str = num2str(value);
            elseif ischar(value) || (isstring(value) && isscalar(value))
                str = char(value);
            else
                str = '<complex>';
            end
        end
    end
end