classdef ValidationReport < handle
    % VALIDATIONREPORT Generate validation report (Markdown)
    %
    % Usage:
    %   report = narwc.reports.ValidationReport(validation_results, survey_id);
    %   report.generate('validation_report.md');
    
    properties (Access = private)
        results
        survey_id
    end
    
    methods
        function obj = ValidationReport(validation_results, survey_id)
            % VALIDATIONREPORT Constructor
            %
            % Inputs:
            %   validation_results - Results from SurveyValidator.validate()
            %   survey_id - Survey identifier
            
            obj.results = validation_results;
            
            if nargin > 1
                obj.survey_id = survey_id;
            else
                obj.survey_id = 'Unknown';
            end
        end
        
        function generate(obj, output_file)
            % GENERATE Generate validation report
            
            % Create output directory
            output_dir = fileparts(output_file);
            if ~isempty(output_dir) && ~exist(output_dir, 'dir')
                mkdir(output_dir);
            end
            
            % Generate markdown
            content = obj.generateMarkdown();
            
            % Write to file
            fid = fopen(output_file, 'w');
            fprintf(fid, '%s', content);
            fclose(fid);
            
            fprintf('Validation report generated: %s\n', output_file);
        end
        
        function md = generateMarkdown(obj)
            % GENERATEMARKDOWN Generate markdown report
            
            md = sprintf('# Validation Report\n\n');
            md = [md sprintf('**Survey:** %s  \n', obj.survey_id)];
            md = [md sprintf('**Generated:** %s  \n\n', char(datetime('now')))];
            md = [md sprintf('---\n\n')];
            
            % Overall status
            md = [md sprintf('## Overall Status\n\n')];
            
            if isfield(obj.results, 'summary')
                summary = obj.results.summary;
                
                if summary.errors == 0
                    md = [md sprintf('✅ **PASSED** - No errors found\n\n')];
                else
                    md = [md sprintf('❌ **FAILED** - %d errors found\n\n', summary.errors)];
                end
                
                md = [md sprintf('- **Errors:** %d\n', summary.errors)];
                md = [md sprintf('- **Warnings:** %d\n', summary.warnings)];
                md = [md sprintf('- **Info:** %d\n\n', summary.info)];
            end
            
            % Errors
            if isfield(obj.results, 'errors') && ~isempty(obj.results.errors)
                md = [md obj.generateErrorSection(obj.results.errors, 'Errors', '❌')];
            end
            
            % Warnings
            if isfield(obj.results, 'warnings') && ~isempty(obj.results.warnings)
                md = [md obj.generateErrorSection(obj.results.warnings, 'Warnings', '⚠️')];
            end
            
            % Info
            if isfield(obj.results, 'info') && ~isempty(obj.results.info)
                md = [md obj.generateErrorSection(obj.results.info, 'Information', 'ℹ️')];
            end
            
            % Issues by field
            if isfield(obj.results, 'summary') && ~isempty(fieldnames(obj.results.summary.by_field))
                md = [md obj.generateIssuesByField()];
            end
            
            % Recommendations
            if isfield(obj.results, 'summary') && obj.results.summary.errors > 0
                md = [md obj.generateRecommendations()];
            end
            
            md = [md sprintf('---\n\n')];
            md = [md sprintf('*Report generated by NARWC Validation System*\n')];
        end
        
        function md = generateErrorSection(obj, errors, title, icon)
            % GENERATEERRORSECTION Generate section for errors/warnings/info
            
            md = sprintf('## %s %s (%d)\n\n', icon, title, length(errors));
            
            % Group by field
            fields = unique({errors.field});
            
            for i = 1:length(fields)
                field = fields{i};
                field_errors = errors(strcmp({errors.field}, field));
                
                md = [md sprintf('### %s (%d issues)\n\n', field, length(field_errors))];
                
                % Show up to 20 issues per field
                max_show = min(20, length(field_errors));
                
                for j = 1:max_show
                    err = field_errors(j);
                    rows_str = obj.formatRows(err.row);
                    md = [md sprintf('- **Row(s) %s:** %s\n', rows_str, err.message)];
                end
                
                if length(field_errors) > max_show
                    md = [md sprintf('\n*... and %d more issues*\n', ...
                        length(field_errors) - max_show)];
                end
                
                md = [md sprintf('\n')];
            end
        end
        
        function md = generateIssuesByField(obj)
            % GENERATEISSUESBYFIELD Summary table of issues by field
            
            md = sprintf('## Issues by Field\n\n');
            md = [md sprintf('| Field | Count |\n')];
            md = [md sprintf('|-------|-------|\n')];
            
            by_field = obj.results.summary.by_field;
            field_names = fieldnames(by_field);
            
            % Sort by count (descending)
            counts = zeros(length(field_names), 1);
            for i = 1:length(field_names)
                counts(i) = by_field.(field_names{i});
            end
            [~, sort_idx] = sort(counts, 'descend');
            
            for i = 1:length(field_names)
                idx = sort_idx(i);
                field = field_names{idx};
                count = by_field.(field);
                md = [md sprintf('| %s | %d |\n', strrep(field, '_', ' '), count)];
            end
            
            md = [md sprintf('\n')];
        end
        
        function md = generateRecommendations(obj)
            % GENERATERECOMMENDATIONS Generate actionable recommendations
            
            md = sprintf('## Recommendations\n\n');
            
            summary = obj.results.summary;
            
            if summary.errors > 0
                md = [md sprintf('This survey has **%d errors** that must be corrected before upload:\n\n', ...
                    summary.errors)];
                
                md = [md sprintf('1. Review all error messages above\n')];
                md = [md sprintf('2. Correct issues in the source data\n')];
                md = [md sprintf('3. Re-run validation\n')];
                md = [md sprintf('4. Upload once all errors are resolved\n\n')];
            end
            
            if summary.warnings > 0
                md = [md sprintf('This survey has **%d warnings** that should be reviewed:\n\n', ...
                    summary.warnings)];
                
                md = [md sprintf('- Warnings indicate potential issues but do not prevent upload\n')];
                md = [md sprintf('- Review warnings to ensure data quality\n')];
                md = [md sprintf('- Consider correcting warning issues if appropriate\n\n')];
            end
        end
        
        function str = formatRows(obj, rows)
            % FORMATROWS Format row numbers for display
            
            if length(rows) == 1
                str = num2str(rows);
            elseif length(rows) <= 5
                str = sprintf('%s', strjoin(arrayfun(@num2str, rows, 'UniformOutput', false), ', '));
            else
                str = sprintf('%d-%d (%d rows)', min(rows), max(rows), length(rows));
            end
        end
    end
end