replace swimdir with 999 for swimdir=0
replace anhead with '00' for swimdir<11.5 .and. anhead='  '
replace anhead with '01' for swimdir<33.5 .and. anhead='  '
replace anhead with '02' for swimdir<56.5 .and. anhead='  '
replace anhead with '03' for swimdir<78.5 .and. anhead='  '
replace anhead with '04' for swimdir<101.5 .and. anhead='  '
replace anhead with '05' for swimdir<123.5 .and. anhead='  '
replace anhead with '06' for swimdir<146.5 .and. anhead='  '
replace anhead with '07' for swimdir<168.5 .and. anhead='  '
replace anhead with '08' for swimdir<191.5 .and. anhead='  '
replace anhead with '09' for swimdir<213.5 .and. anhead='  '
replace anhead with '10' for swimdir<236.5 .and. anhead='  '
replace anhead with '11' for swimdir<258.5 .and. anhead='  '
replace anhead with '12' for swimdir<281.5 .and. anhead='  '
replace anhead with '13' for swimdir<303.5 .and. anhead='  '
replace anhead with '14' for swimdir<326.5 .and. anhead='  '
replace anhead with '15' for swimdir<348.5 .and. anhead='  '
replace anhead with '00' for swimdir<360.1 .and. anhead='  '
replace anhead with '21' for behav1='st'
replace anhead with '22' for behav1='an'
RETURN

