     IF FILEID = '  ' THEN DO;
        FLAG = 'FILE ID NUMBER MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF EVENTNO = . THEN DO;
        FLAG = 'EVENT NUMBER MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF YEAR = . THEN DO;
        FLAG = 'YEAR MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF FID1 = 'A' OR FID1 = 'F' OR FID1 = 'P' OR FID1 = 'O' OR FID1 = 'H'
        THEN DO;
        yr = 1900 + substr(fileid,3,2);
        END;
     ELSE IF FID1 = 'a' OR FID1 = 'f' OR FID1 = 'p' OR FID1 = 'o'
        OR FID1 = 'c' THEN DO;
        yr = 2000 + substr(fileid,3,2);
        END;
     if yr ne year then do;
        flag = 'YEAR/FILEID MISMATCH';
        badvalue = year;
        output;
        end;
     IF MONTH = . THEN DO;
        FLAG = 'MONTH MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF LATDEG = . THEN DO;
        FLAG = 'LATDEG MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF LATMIN = . THEN DO;
        FLAG = 'LATMIN MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF LONGDEG = . THEN DO;
        FLAG = 'LONGDEG MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF LONGMIN = . THEN DO;
        FLAG = 'LONGMIN MISSING';
        BADVALUE = ' ';
        OUTPUT;
        END;
     IF BEAUFORT GT 7 AND BEAUFORT NE 9 THEN DO;
        FLAG = 'BEAUFORT OVER 7';
        BADVALUE = BEAUFORT;
        OUTPUT;
        END;
     IF CLOUD NE . AND (5 le CLOUD le 8 OR CLOUD > 9)
        THEN DO;
        FLAG = 'CLOUD COVER OUT OF RANGE';
        BADVALUE = CLOUD;
        OUTPUT;
        END;
     IF (DAY=0 OR DAY GT 31 OR (MONTH=2 AND DAY GT 29) OR
        ((MONTH=4 OR MONTH=6 OR MONTH=9 OR MONTH=11) AND
        DAY GT 30)) THEN DO;
        FLAG = 'DAY OUT OF RANGE';
        BADVALUE = DAY;
        OUTPUT;
        END;
*     IF DEBRIS GT 7 THEN DO;
 *       FLAG = 'DEBRIS OUT OF RANGE';
  *      BADVALUE = DEBRIS;
   *     OUTPUT;
    *    END;
     IF HEADING GT 359 THEN DO;
        FLAG = 'HEADING OUT OF RANGE';
        BADVALUE = HEADING;
        OUTPUT;
        END;
*     IF HUMANACT GT 46 THEN DO;
 *       FLAG = 'HUMANACT OUT OF RANGE';
  *      BADVALUE = HUMANACT;
   *     OUTPUT;
    *    END;
     IF (LATDEG LT 25 OR LATDEG GT 48) THEN DO;
        FLAG = 'LATDEG OUT OF RANGE';
        BADVALUE = LATDEG;
        OUTPUT;
        END;
     IF LATMIN GE 60.0 THEN DO;
        FLAG = 'LATMIN OUT OF RANGE';
        BADVALUE = LATMIN;
        OUTPUT;
        END;
     IF (LONGDEG LT 58 OR LONGDEG GT 81) THEN DO;
        FLAG = 'LONGDEG OUT OF RANGE';
        BADVALUE = LONGDEG;
        OUTPUT;
        END;
     IF LONGMIN GE 60.0 THEN DO;
        FLAG = 'LONGMIN OUT OF RANGE';
        BADVALUE = LONGMIN;
        OUTPUT;
        END;
     IF MONTH>12 THEN DO;
        FLAG = 'MONTH OUT OF RANGE';
        BADVALUE = MONTH;
        OUTPUT;
        END;
     IF SURFTEMP NE . AND (SURFTEMP LT -2 OR SURFTEMP GT 35)
        THEN DO;
        FLAG = 'TEMPERATURE OUT OF RANGE';
        BADVALUE = SURFTEMP;
        OUTPUT;
        END;
     IF TIME = . THEN DO;
        IF UPCASE(FID1) NE 'O' THEN DO;
        FLAG = 'TIME MISSING';
        BADVALUE = TIME;
        OUTPUT;
        END;
        END;
     ELSE IF TIME GE 240000 OR TIME LT 0 THEN DO;
        FLAG = 'TIME OUT OF RANGE';
        BADVALUE = TIME;
        OUTPUT;
        END;
     IF WX NE 'B' AND WX NE 'C' AND WX NE 'D' AND WX NE 'F' AND WX NE 'G' 
        AND WX NE 'H' AND WX NE 'L' AND WX NE 'P' AND WX NE 'R' AND WX NE 'S' 
        AND WX NE 'T' AND WX NE 'X' and wx ne ' ' THEN DO;
        FLAG = 'BAD WEATHER CODE';
        BADVALUE = WX;
        OUTPUT;
        END;
     IF YEAR < 1990 or year > 2018 THEN DO;
        FLAG = 'YEAR OUT OF RANGE';
        BADVALUE = YEAR;
        OUTPUT;
        END;
