     IF GLAREL > 3 THEN DO;
        FLAG = 'LEFT GLARE OUT OF RANGE';
        BADVALUE = GLAREL;
        OUTPUT;
        END;
     IF GLARER > 3 THEN DO;
        FLAG = 'RIGHT GLARE OUT OF RANGE';
        BADVALUE = GLARER;
        OUTPUT;
        END;
     LAT = (LATDEG + LATMIN/60)/57.29678;
     LONG = (LONGDEG + LONGMIN/60)/57.29678;
     IF TIME < 2400 THEN DO;
        TIMEHR = INT(TIME/100);
        TIMEMIN = TIME - 100*TIMEHR;
        TIMESEC = 0;
        END;
     ELSE IF TIME > 2400 THEN DO;
        TIMEHR = INT(TIME/10000);
        TIMEMIN = INT((TIME - TIMEHR*10000)/100) ;
        TIMESEC = TIME - 10000*TIMEHR - 100*TIMEMIN;
        END;
     IF TIMEMIN GT 59 THEN DO;
        FLAG = 'TIME MINUTES OUT OF RANGE';
        BADVALUE = TIME;
        OUTPUT;
        END;
     IF TIMESEC GT 59 THEN DO;
        FLAG = 'TIME SECONDS OUT OF RANGE';
        BADVALUE = TIME;
        OUTPUT;
        END;
     TIME2 = TIMEHR + TIMEMIN/60 + TIMESEC/3600;
     PREVLAT = LAG(LAT);
     PREVLONG = LAG(LONG);
     PREVTIME = LAG(TIME2);
     PREVALT  = LAG(ALT);
     DISTANCE = 60 * 57.29678 * ARCOS((SIN(PREVLAT) *
                SIN(LAT)) + (COS(PREVLAT) * COS(LAT)) *
                COS(LONG - PREVLONG));
     ETIME = TIME2 - PREVTIME;
     IF (ETIME NE . AND ETIME LT 0) THEN DO;
        FLAG = 'TIMES OUT OF ORDER';
        BADVALUE = ETIME;
        OUTPUT;
        END;
     ELSE IF ETIME>0.0333 THEN DO;
        FLAG = '>2 MINUTES WITHOUT A POSITION';
        BADVALUE = ETIME*60;
        OUTPUT;
        END;
     SPEED = DISTANCE/ETIME;
     IF ETIME = 0 THEN DO;
        DELTA = round(((ALT - PREVALT)*0.0546833)/0.000278);
        END;
     ELSE IF ETIME > 0 THEN DO;
        DELTA = round(((ALT - PREVALT)*0.0546833)/etime);
        END;        
        IF ALT = . THEN DO;
           FLAG = 'ALTITUDE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        ELSE IF (ALT LT 60 OR ALT GT 750) THEN DO;
           FLAG = 'ALT OUT OF RANGE';
           BADVALUE = ALT;
           OUTPUT;
           END;
        IF DELTA > 1200 AND PLATFORM = 649 THEN DO;
           FLAG = 'CLIMB > 1200 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA < -1800 AND PLATFORM = 649 THEN DO;
           FLAG = 'DESCENT > 1800 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA > 1200 AND (PLATFORM=633 or PLATFORM=653) THEN DO;
           FLAG = 'CLIMB > 1600 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA < -2400 AND (PLATFORM=633 or PLATFORM=653) THEN DO;
           FLAG = 'DESCENT > 2400 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA > 1000 and platform ne 649 and platform ne 633
             and platform ne 653 THEN DO;
           FLAG = 'CLIMB > 1000 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA < -1500 and platform ne 649 and platform ne 633
             and platform ne 653 THEN DO;
           FLAG = 'DESCENT > 1500 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        IF DAY = . THEN DO;
           FLAG = 'DAY MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF TIME = . THEN DO;
           FLAG = 'TIME MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF LEGTYPE = . THEN DO;
           FLAG = 'LEGTYPE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF BEAUFORT = . THEN DO;
           FLAG = 'BEAUFORT MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF CLOUD = . THEN DO;
           FLAG = 'CLOUD COVER MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF WX = ' ' THEN DO;
           FLAG = 'WEATHER CODE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF VISIBLTY = . THEN DO;
           FLAG = 'VISIBILITY MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;        
        IF HEADING = . THEN DO;
           FLAG = 'HEADING MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF LEGTYPE GT 4 AND LEGTYPE NE 7 THEN DO;
           FLAG = 'LEGTYPE OUT OF RANGE';
           BADVALUE = LEGTYPE;
           OUTPUT;
           END;
        IF LEGTYPE=2 AND LEGSTAGE = . THEN DO;
              FLAG = 'LEG STAGE MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
        IF (LEGTYPE=2 OR LEGTYPE=4) AND LEGNO = . THEN DO;
              FLAG = 'LEG NUMBER MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
        IF LEGTYPE=2 THEN DO;
           IF GLAREL = . THEN DO;
              FLAG = 'LEFT GLARE MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           IF GLARER = . THEN DO;
              FLAG = 'RIGHT GLARE MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           END;
        IF LEGTYPE NE 2 AND LEGSTAGE NE . THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LEGTYPE=2 AND LEGSTAGE GT 5 THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END; 
        IF LEGTYPE=2 AND LEGSTAGE=1 AND (LAG(LEGSTAGE)=2 
           OR LAG(LEGSTAGE)=3 OR LAG(LEGSTAGE=4)) THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LEGTYPE=2 AND LEGSTAGE=2 AND (LAG(LEGSTAGE)=3 
           OR LAG(LEGSTAGE=5) OR LAG(LEGTYPE) NE 2) THEN DO; 
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LEGTYPE=2 AND LEGSTAGE=3 AND (LAG(LEGSTAGE)=3 
           OR LAG(LEGSTAGE)=5 OR LAG(LEGTYPE) NE 2) THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LEGTYPE=2 AND LEGSTAGE=4 AND
           (LAG(LEGSTAGE) NE 3 AND LAG(LEGTYPE) NE 4) THEN DO; 
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LEGTYPE=2 AND LEGSTAGE=5 AND
           (LAG(LEGSTAGE)=1 OR LAG(LEGSTAGE)=3) THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LEGTYPE=4 AND (LAG(LEGTYPE) NE 4 AND
           LAG(LEGSTAGE) NE 3) THEN DO; 
           FLAG = 'LEG TYPE OUT OF RANGE';
           BADVALUE = LEGTYPE;
           OUTPUT;
           END;
        IF LAST.FILEID AND (LEGSTAGE NE 5 AND LEGSTAGE NE .)
           THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF ETIME = 0 AND DISTANCE = 0 THEN DO;
           FLAG = 'DUPLICATE LOCATION & TIME';
           OUTPUT;
           END;
        ELSE IF ETIME > 0 AND DISTANCE = 0 THEN DO;
           FLAG = 'SAME LOCATION, DIFF. TIME';
           OUTPUT;
           END;
        ELSE IF ETIME = 0 AND DISTANCE > 0 THEN DO;
           SPEED = DISTANCE / 0.000278;
           END;
        IF SPEED GT 225 THEN DO;
           FLAG = 'SPEED TOO HIGH';
           BADVALUE = SPEED;
           OUTPUT;
           END;
        ELSE IF (0.5 LE SPEED < 50) AND DISTANCE > 0 THEN DO;
           FLAG = 'SPEED TOO LOW';
           BADVALUE = SPEED;
           OUTPUT;
           END;
        ELSE IF (0 < SPEED < 0.5) AND ETIME=0 THEN DO;
           FLAG = 'DUPLICATE LOCATION & TIME';
           OUTPUT;
           END;
        ELSE IF (0 < SPEED < 0.5) AND ETIME>0 THEN DO;
           FLAG = 'SAME LOCATION, DIFF. TIME';
           OUTPUT;
           END;
        IF (PLATFORM LT 626 OR PLATFORM GT 649) THEN DO;
           FLAG = 'PLATFORM NUMBER OUT OF RANGE';
           BADVALUE = PLATFORM;
           OUTPUT;
           END;

 