**********************************************************************
*****                                                            *****
*****     THIS MACRO INCLUDES THE SAS CODE NECESSARY TO CHECK    *****
*****     THAT ALL VARIABLES (EXCEPT FOR SIGHTING, DEBRIS,       *****
*****     HUMANACT FIELDS) ARE IDENTICAL WHERE THE SAME EVENT    *****
*****     NUMBER IS DUPLICATED IN SUCCESSIVE RECORDS.  IN        *****
*****     MOST CASES THOSE WILL BE ERRORS AND EVENT NUMBERS      *****
*****     WILL NEED TO BE CHANGED.  THIS FILE IS READ-ONLY,      *****
*****     WHICH MUST BE CHANGED (IN WINDOWS EXPLORER) TO EDIT.   *****
*****     THE FILE IS INVOKED FROM WITHIN THE SAS QUALITY        *****
*****     CONTROL PROCESS.                                       *****
*****                                                            *****
*****               PROGRAMMER:  R. D. KENNEY                    *****
*****          LATEST REVISION:  22 FEBRUARY 2010                *****
*****                                                            *****
**********************************************************************;
  P_EVNT = LAG1(EVENTNO);
  P_SIT  = LAG1(SIGHTNO);
  P_TIME = LAG1(TIME);
  P_MNTH = LAG1(MONTH);
  P_DAY  = LAG1(DAY);
  P_YEAR = LAG1(YEAR);
  P_LTDG = LAG1(LATDEG);
  P_LTMN = LAG1(LATMIN);
  P_LGDG = LAG1(LONGDEG);
  P_LGMN = LAG1(LONGMIN);
  P_LTYP = LAG1(LEGTYPE);
  P_LSTG = LAG1(LEGSTAGE);
  P_HDNG = LAG1(HEADING);
  P_ALT  = LAG1(ALT);
  P_TEMP = LAG1(SURFTEMP);
  P_DPTH = LAG1(DEPTH);
  P_VIZ  = LAG1(VISIBLTY);
  P_BFT  = LAG1(BEAUFORT);
  P_CLD  = LAG1(CLOUD);
  P_WX   = LAG1(WX);
  P_LGLR = LAG1(GLAREL);
  P_RGLR = LAG1(GLARER);
IF P_EVNT = EVENTNO THEN DO;
   IF P_SIT=. OR SIGHTNO=. THEN DO;
      FLAG = 'REPEAT EVENTS OTHER THAN SIGHTINGS';
      BADVALUE = SIGHTNO;
      OUTPUT;
      END; 
   IF P_TIME NE TIME THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED TIMES';
      BADVALUE = TIME;
      OUTPUT;
      END;
   IF P_MNTH NE MONTH THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED MONTHS';
      BADVALUE = MONTH;
      OUTPUT;
      END;
   IF P_DAY NE DAY THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED DAYS';
      BADVALUE = DAY;
      OUTPUT;
      END;
   IF P_YEAR NE YEAR THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED YEARS';
      BADVALUE = YEAR;
      OUTPUT;
      END;
   IF P_LTDG NE LATDEG THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED LATDEGS';
      BADVALUE = LATDEG;
      OUTPUT;
      END;
   IF P_LTMN NE LATMIN THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED LATMINS';
      BADVALUE = LATMIN;
      OUTPUT;
      END;
   IF P_LGDG NE LONGDEG THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED LONGDEGS';
      BADVALUE = LONGDEG;
      OUTPUT;
      END;
   IF P_LGMN NE LONGMIN THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED LONGMINS';
      BADVALUE = LONGMIN;
      OUTPUT;
      END;
   IF P_LTYP NE LEGTYPE THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED LEGTYPES';
      BADVALUE = LEGTYPE;
      OUTPUT;
      END;
   IF P_LSTG NE LEGSTAGE THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED LEGSTAGES';
      BADVALUE = LEGSTAGE;
      OUTPUT;
      END;
   IF P_HDNG NE HEADING THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED HEADINGS';
      BADVALUE = HEADING;
      OUTPUT;
      END;
   IF P_ALT NE ALT THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED ALTITUDES';
      BADVALUE = ALT;
      OUTPUT;
      END;
   IF P_TEMP NE SURFTEMP THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED SURFTEMPS';
      BADVALUE = SURFTEMP;
      OUTPUT;
      END;
   IF P_DPTH NE DEPTH THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED DEPTHS';
      BADVALUE = DEPTH;
      OUTPUT;
      END;
   IF P_VIZ NE VISIBLTY THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED VISIBILITIES';
      BADVALUE = VISIBLTY;
      OUTPUT;
      END;
   IF P_BFT NE BEAUFORT THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED SEA STATES';
      BADVALUE = BEAUFORT;
      OUTPUT;
      END;
   IF P_CLD NE CLOUD THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED CLOUD COVERS';
      BADVALUE = CLOUD;
      OUTPUT;
      END;
   IF P_WX NE WX THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED WEATHER CODES';
      BADVALUE = WX;
      OUTPUT;
      END;
   IF P_LGLR NE GLAREL THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED LEFT GLARES';
      BADVALUE = GLAREL;
      OUTPUT;
      END;
   IF P_RGLR NE GLARER THEN DO;
      FLAG = 'REPEAT EVENTS W/ MISMATCHED RIGHT GLARES';
      BADVALUE = GLARER;
      OUTPUT;
      END;
   END;
