     LAT = (LATDEG + LATMIN/60)/57.29678;
     LONG = (LONGDEG + LONGMIN/60)/57.29678;
     TIMEHR = INT(TIME/10000);
     TIMEMIN = int((TIME - 10000*TIMEHR)/100);
     timesec = time - 10000*timehr - 100*timemin;
     pday = lag1(day);
     pmonth = lag1(month);
     if pmonth ne month and eventno>1 then do;
        flag = 'MONTH MISMATCH';
        badvalue = month;
        output;
        end;
     if pday ne day and eventno>1 then do;
        flag = 'DAY MISMATCH';
        badvalue = day;
        output;
        end;
     IF TIMEMIN GT 59 THEN DO;
        FLAG = 'TIME MINUTES OUT OF RANGE';
        BADVALUE = TIME;
        OUTPUT;
        END;
     IF TIMEsec GT 59 THEN DO;
        FLAG = 'TIME SECONDS OUT OF RANGE';
        BADVALUE = TIME;
        OUTPUT;
        END;
     TIME2 = TIMEHR + TIMEMIN/60 + timesec/3600;
     PREVLAT = LAG(LAT);
     PREVLONG = LAG(LONG);
     PREVDAY = LAG(DAY);
     PREVTIME = LAG(TIME2);
     DISTANCE = 60 * 57.29678 * ARCOS((SIN(PREVLAT) *
                SIN(LAT)) + (COS(PREVLAT) * COS(LAT)) *
                COS(LONG - PREVLONG));
     IF DAY = PREVDAY THEN DO;
        ETIME = TIME2 - PREVTIME;
        END;
     ELSE DO;
        ETIME = TIME2 + 24*(DAY-PREVDAY) - PREVTIME;
        END;
     IF ETIME = 0 THEN ETIME = 0.0003;
     ELSE IF (ETIME NE . AND ETIME LT 0) THEN DO;
        FLAG = 'TIMES OUT OF ORDER';
        BADVALUE = ETIME;
        OUTPUT;
        END;
     SPEED = DISTANCE/ETIME;
        IF ALT > 0 THEN DO;
           FLAG = 'VESSEL IS AIRBORNE!!!';
           BADVALUE = ALT;
           OUTPUT;
           END;
        IF DAY = . THEN DO;
           FLAG = 'DAY MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF TIME = . THEN DO;
           FLAG = 'TIME MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF LEGTYPE = . THEN DO;
           FLAG = 'LEGTYPE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF LEGSTAGE NE . THEN DO;
           IF BEAUFORT = . THEN DO;
              FLAG = 'BEAUFORT MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           IF CLOUD = . THEN DO;
              FLAG = 'CLOUD COVER MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           IF VISIBLTY = . THEN DO;
              FLAG = 'VISIBILITY MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           END;
        IF ((LAG(LEGSTAGE)=1 OR LAG(LEGSTAGE)=2) AND LEGSTAGE=.)
           THEN DO;
           FLAG = 'LEG STAGE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF LEGTYPE NE . AND (LEGTYPE LT 5 OR LEGTYPE GT 6)
           THEN DO;
           FLAG = 'LEGTYPE OUT OF RANGE';
           BADVALUE = LEGTYPE;
           OUTPUT;
           END;
        IF LEGSTAGE NE . AND
           ((LEGSTAGE NE 1 AND LEGSTAGE NE 2 AND LEGSTAGE NE 5)
           OR (LAG(LEGSTAGE)=1 AND LEGSTAGE=1) OR
           (LAG(LEGSTAGE)=2 AND LEGSTAGE=1) OR (LAG(LEGSTAGE)=5
           AND LEGSTAGE=2)) THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LAST.FILEID AND (LEGSTAGE NE 5 AND LEGSTAGE NE .)
           THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF SPEED GT 25 THEN DO;
           FLAG = 'SPEED TOO HIGH';
           BADVALUE = SPEED;
           OUTPUT;
           END;
