     LAT = (LATDEG + LATMIN/60)/57.29678;
     LONG = (LONGDEG + LONGMIN/60)/57.29678;
     pday = lag1(day);
     pmonth = lag1(month);
     if pmonth ne month and eventno>1 then do;
        flag = 'MONTH MISMATCH';
        badvalue = month;
        output;
        end;
     if pday ne day and eventno>1 then do;
        flag = 'DAY MISMATCH';
        badvalue = day;
        output;
        end;
     TIMEHR = INT(TIME/10000);
     TIMEMIN = INT((TIME - TIMEHR*10000)/100) ;
     TIMESEC = TIME - 10000*TIMEHR - 100*TIMEMIN;
*timesec=0;
     IF TIMEMIN GT 59 THEN DO;
        FLAG = 'TIME MINUTES OUT OF RANGE';
        BADVALUE = TIME;
        OUTPUT;
        END;
     IF TIMESEC GT 59 THEN DO;
        FLAG = 'TIME SECONDS OUT OF RANGE';
        BADVALUE = TIME;
        OUTPUT;
        END;
     TIME2 = TIMEHR + TIMEMIN/60 + TIMESEC/3600;
     PREVLAT = LAG(LAT);
     PREVLONG = LAG(LONG);
     PREVTIME = LAG(TIME2);
     PREVALT  = LAG(ALT);
     PREVSST  = LAG(SURFTEMP);
     DISTANCE = 60 * 57.29678 * ARCOS((SIN(PREVLAT) *
                SIN(LAT)) + (COS(PREVLAT) * COS(LAT)) *
                COS(LONG - PREVLONG));
     ETIME = TIME2 - PREVTIME;
     IF ETIME = 0 THEN DO;
        DELTA = round(((ALT - PREVALT)*0.0546833)/0.000278);
        END;
     ELSE IF ETIME > 0 THEN DO;
        DELTA = round(((ALT - PREVALT)*0.0546833)/etime);
        END;        
     IF ETIME = 0 THEN ETIME = 0.00028;
     ELSE IF (ETIME NE . AND ETIME LT 0) THEN DO;
        FLAG = 'TIMES OUT OF ORDER';
        BADVALUE = ETIME;
        OUTPUT;
        END;
     ELSE IF (ETIME>0.25 AND (LEGSTAGE=2 OR LEGSTAGE=5)) THEN DO;
        FLAG = '>15 MINUTES WITHOUT A POSITION';
        BADVALUE = ETIME*60;
        OUTPUT;
        END;
     SPEED = DISTANCE/ETIME;
     SSTDIFF  = SURFTEMP - PREVSST;
     GRADIENT = ABS(SSTDIFF/DISTANCE);
        IF ALT = . THEN DO;
           FLAG = 'ALTITUDE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        ELSE IF (ALT LT 60 OR ALT GT 750) THEN DO;
           FLAG = 'ALT OUT OF RANGE';
           BADVALUE = ALT;
           OUTPUT;
           END;
        ELSE IF ALT = 999 THEN DO;
           FLAG = 'BOGUS ALTITUDE';
           BADVALUE = ALT;
           OUTPUT;
           END;
        IF DELTA > 1200 AND PLATFORM = 649 THEN DO;
           FLAG = 'CLIMB > 1200 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA < -1800 AND PLATFORM = 649 THEN DO;
           FLAG = 'DESCENT > 1800 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA > 1600 AND (PLATFORM=633 or PLATFORM=653) THEN DO;
           FLAG = 'CLIMB > 1600 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA < -2400 AND (PLATFORM=633 or PLATFORM=653) THEN DO;
           FLAG = 'DESCENT > 2400 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA > 1000 and platform ne 649 and platform ne 633
             and platform ne 653 THEN DO;
           FLAG = 'CLIMB > 1000 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        ELSE IF DELTA < -1500 and platform ne 649 and platform ne 633
             and platform ne 653 THEN DO;
           FLAG = 'DESCENT > 1500 FT/MIN';
           BADVALUE = DELTA;
           OUTPUT;
           END;
        if beaufort>7 then do;
           flag = 'BEAUFORT OUT OF RANGE';
           BADVALUE = BEAUFORT;
           OUTPUT;
           END;
        IF DAY = . THEN DO;
           FLAG = 'DAY MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF GLAREL GT 3 THEN DO;
           FLAG = 'LEFT GLARE OUT OF RANGE';
           BADVALUE = GLAREL;
           OUTPUT;
           END;
        IF GLARER GT 3 THEN DO;
           FLAG = 'RIGHT GLARE OUT OF RANGE';
           BADVALUE = GLARER;
           OUTPUT;
           END;
        IF TIME = . THEN DO;
           FLAG = 'TIME MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF VISIBLTY>35 THEN DO;
           FLAG = 'VISIBLTY TOO HIGH';
           BADVALUE = VISIBLTY;
           OUTPUT;
           END;
        IF LEGTYPE = . THEN DO;
           FLAG = 'LEGTYPE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF LEGSTAGE NE . THEN DO;
           IF BEAUFORT = . THEN DO;
              FLAG = 'BEAUFORT MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           IF CLOUD = . THEN DO;
              FLAG = 'CLOUD COVER MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           if wx = ' ' then do;
              flag = 'WEATHER CODE MISSING';
              BADVALUE = ' ';
              OUTPUt;
              end;
           IF VISIBLTY = . THEN DO;
              FLAG = 'VISIBILITY MISSING';
              BADVALUE = ' ';
              OUTPUT;
              END;
           END;
        IF ((LAG(LEGSTAGE)=1 OR LAG(LEGSTAGE)=2) AND LEGSTAGE=.)
           THEN DO;
           FLAG = 'LEG STAGE MISSING';
           BADVALUE = ' ';
           OUTPUT;
           END;
        IF LEGTYPE NE 7 AND LEGTYPE NE 9 THEN DO;
           FLAG = 'LEGTYPE OUT OF RANGE';
           BADVALUE = LEGTYPE;
           OUTPUT;
           END;
        IF LEGSTAGE NE . AND
           ((LEGSTAGE NE 1 AND LEGSTAGE NE 2 AND LEGSTAGE NE 5)
           OR (LAG(LEGSTAGE)=1 AND LEGSTAGE=1) OR
           (LAG(LEGSTAGE)=2 AND LEGSTAGE=1) OR (LAG(LEGSTAGE)=5
           AND (LEGSTAGE=2 or LEGSTAGE=5)) OR (LAG(LEGSTAGE)=.
           AND (LEGSTAGE=2 OR LEGSTAGE=5))) THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF LAST.FILEID AND (LEGSTAGE NE 5 AND LEGSTAGE NE .)
           THEN DO;
           FLAG = 'LEG STAGE OUT OF RANGE';
           BADVALUE = LEGSTAGE;
           OUTPUT;
           END;
        IF SPEED GT 200 and platform ne 654 THEN DO;
           FLAG = 'SPEED TOO HIGH';
           BADVALUE = SPEED;
           OUTPUT;
           END;
        if speed lt 25 AND DISTANCE>0 then do;
           flag = 'SPEED TOO LOW';
           badvalue = speed;
           output;
           end;
        IF SPEED GT 130 and platform = 654 THEN DO;
           FLAG = 'SPEED TOO HIGH';
           BADVALUE = SPEED;
           OUTPUT;
           END;
        IF GRADIENT>0.5 AND SSTDIFF>1 THEN DO;
           FLAG = 'SST TOO VARIABLE';
           BADVALUE = GRADIENT;
           OUTPUT;
           END;
        IF (PLATFORM LT 600 OR PLATFORM GT 699) THEN DO;
           FLAG = 'PLATFORM NUMBER OUT OF RANGE';
           BADVALUE = PLATFORM;
           OUTPUT;
           END;
