**********************************************************************
*****                                                            *****
*****     THIS FILE INCLUDES THE SAS CODE NECESSARY TO CHECK     *****
*****     SIGHTINGS FOR MISSING SPECIES AND TAXON CODES AND      *****
*****     FOR ALLOWABLE VALUES OF SPECIES CODES.  WHEN NEW       *****
*****     SPECIES CODES ARE ASSIGNED, THE APPROPRIATE LINES      *****
*****     MUST BE ADDED HERE BY THE DATABASE MANAGER.  THIS      *****
*****     FILE IS READ-ONLY, WHICH MUST BE CHANGED TO EDIT.      *****
*****     THE FILE IS INVOKED FROM WITHIN THE SAS QUALITY-       *****
*****     CONTROL PROCESS VIAS THE %INCLUDE COMMAND.             *****
*****                                                            *****
*****               PROGRAMMER:  R. D. KENNEY                    *****
*****          LATEST REVISION:  23 MARCH 2015                   *****
*****                                                            *****
**********************************************************************;
        IF SPECCODE = ' ' THEN DO;
           FLAG = 'MISSING SPECIES CODE';
           OUTPUT;
           END;
        ELSE IF (SPECCODE NE 'BASH' AND SPECCODE NE 'BELU' AND
           SPECCODE NE 'BEWH' AND SPECCODE NE 'BLSH' AND
           SPECCODE NE 'BLWH' AND SPECCODE NE 'BODO' AND
           SPECCODE NE 'FIWH' AND SPECCODE NE 'FKWH' AND
           SPECCODE NE 'GOBW' AND SPECCODE NE 'GRAM' AND
           SPECCODE NE 'GRSE' AND SPECCODE NE 'GRTU' AND
           SPECCODE NE 'HAPO' AND SPECCODE NE 'HASE' AND
           SPECCODE NE 'HHSH' AND SPECCODE NE 'HUWH' AND
           SPECCODE NE 'KIWH' AND SPECCODE NE 'LETU' AND
           SPECCODE NE 'LOTU' AND SPECCODE NE 'MIWH' AND
           SPECCODE NE 'NBWH' AND SPECCODE NE 'OCSU' AND
           SPECCODE NE 'OTBI' AND SPECCODE NE 'PIWH' AND
           SPECCODE NE 'PSWH' AND SPECCODE NE 'PYKW' AND
           SPECCODE NE 'RITU' AND SPECCODE NE 'RIWH' AND
           SPECCODE NE 'RTDO' AND SPECCODE NE 'SADO' AND
           SPECCODE NE 'SCFI' AND SPECCODE NE 'SCRA' AND
           SPECCODE NE 'SEWH' AND SPECCODE NE 'WTSH' AND
           SPECCODE NE 'SNDO' AND SPECCODE NE 'SPDO' AND
           SPECCODE NE 'SPWH' AND SPECCODE NE 'STDO' AND
           SPECCODE NE 'SWFI' AND SPECCODE NE 'TUNS' AND
           SPECCODE NE 'UNBA' AND SPECCODE NE 'UNBF' AND
           SPECCODE NE 'UNBW' AND SPECCODE NE 'UNDO' AND
           SPECCODE NE 'UNCE' AND SPECCODE NE 'UNMM' AND
           SPECCODE NE 'UNFI' AND SPECCODE NE 'UNFS' AND
           SPECCODE NE 'UNGD' AND SPECCODE NE 'UNLD' AND
           SPECCODE NE 'UNLW' AND SPECCODE NE 'UNMW' AND
           SPECCODE NE 'UNRO' AND SPECCODE NE 'UNSH' AND
           SPECCODE NE 'UNST' AND SPECCODE NE 'UNTU' AND
           SPECCODE NE 'WBDO' AND SPECCODE NE 'WSDO' AND
           SPECCODE NE 'MANA' AND SPECCODE NE 'MARA' AND
           SPECCODE NE 'UNRA' AND SPECCODE NE 'CNRA' AND
           SPECCODE NE 'FLFI' AND SPECCODE NE 'UNSE' AND
           SPECCODE NE 'UNWH' AND SPECCODE NE 'UNSB' AND
           SPECCODE NE 'ASDO' AND SPECCODE NE 'PSDO' AND
           SPECCODE NE 'MHWH' AND SPECCODE NE 'CLDO' AND
           SPECCODE NE 'AMAL' AND SPECCODE NE 'UNID' AND
           SPECCODE NE 'WHSH' AND SPECCODE NE 'BFTU' AND
           SPECCODE NE 'HATU' AND SPECCODE NE 'UNCW' AND
           SPECCODE NE 'BRWH' AND SPECCODE NE 'FRDO' AND
           SPECCODE NE 'UNBS' AND SPECCODE NE 'CG-B' AND
           SPECCODE NE 'CG-C' AND SPECCODE NE 'CG-U' AND
           SPECCODE NE 'CRSH' AND SPECCODE NE 'DE-F' AND
           SPECCODE NE 'DE-J' AND SPECCODE NE 'DE-O' AND
           SPECCODE NE 'DE-P' AND SPECCODE NE 'DE-R' AND
           SPECCODE NE 'DE-S' AND SPECCODE NE 'DE-U' AND
           SPECCODE NE 'DE-W' AND SPECCODE NE 'DR-D' AND
           SPECCODE NE 'DR-T' AND SPECCODE NE 'DR-U' AND
           SPECCODE NE 'DR-W' AND SPECCODE NE 'FE-H' AND
           SPECCODE NE 'FE-S' AND SPECCODE NE 'FE-U' AND
           SPECCODE NE 'FG-C' AND SPECCODE NE 'FG-D' AND
           SPECCODE NE 'FG-G' AND SPECCODE NE 'FG-I' AND
           SPECCODE NE 'FG-L' AND SPECCODE NE 'FG-O' AND
           SPECCODE NE 'FG-U' AND SPECCODE NE 'FV-C' AND
           SPECCODE NE 'FV-D' AND SPECCODE NE 'FV-G' AND
           SPECCODE NE 'FV-H' AND SPECCODE NE 'FV-L' AND
           SPECCODE NE 'FV-P' AND SPECCODE NE 'FV-S' AND
           SPECCODE NE 'FV-T' AND SPECCODE NE 'FV-U' AND
           SPECCODE NE 'KAYK' AND SPECCODE NE 'TISH' AND
           SPECCODE NE 'LE-V' and SPECCODE NE 'MV-B' AND
           SPECCODE NE 'MV-C' AND SPECCODE NE 'MV-L' AND
           SPECCODE NE 'MV-O' AND SPECCODE NE 'MV-S' AND
           SPECCODE NE 'MV-T' AND SPECCODE NE 'MV-U' AND
           SPECCODE NE 'NV-L' AND SPECCODE NE 'NV-S' AND
           SPECCODE NE 'NV-U' AND SPECCODE NE 'OI-D' AND
           SPECCODE NE 'OI-L' AND SPECCODE NE 'OI-P' AND
           SPECCODE NE 'OI-S' AND SPECCODE NE 'RECV' AND
           SPECCODE NE 'RV-L' AND SPECCODE NE 'RV-S' AND
           SPECCODE NE 'SPFV' AND SPECCODE NE 'SV-L' AND
           SPECCODE NE 'SV-S' AND SPECCODE NE 'WHAL' AND
           SPECCODE NE 'FRNT' AND SPECCODE NE 'HPSE' AND
           SPECCODE NE 'ZOOP' AND SPECCODE NE 'FV-F' AND
           SPECCODE NE 'PIBO' AND SPECCODE NE 'SV-U' AND
           SPECCODE NE 'HELO' AND SPECCODE NE 'JETS' AND
           SPECCODE NE 'DE-B' AND SPECCODE NE 'UNVE' AND
           SPECCODE NE 'DE-G' AND SPECCODE NE 'BLBW' AND
           SPECCODE NE 'SOBW' AND SPECCODE NE 'GEBW' AND
           SPECCODE NE 'MY-S' AND SPECCODE NE 'MY-L' AND
           SPECCODE NE 'LFPW' AND SPECCODE NE 'ORTU' AND
           SPECCODE NE 'SFPW' AND SPECCODE NE 'RV-U' AND
           SPECCODE NE 'FV-W' AND SPECCODE NE 'FV-Z' AND
           SPECCODE NE 'ANSH' AND SPECCODE NE 'DSWH' AND
           SPECCODE NE 'GRWH' AND SPECCODE NE 'HGSE' AND
           SPECCODE NE 'HOSE' AND SPECCODE NE 'OBDO' AND
           SPECCODE NE 'POBE' AND SPECCODE NE 'TRBW' AND
           SPECCODE NE 'UNKO' AND SPECCODE NE 'ABDU' AND
           SPECCODE NE 'ARTE' AND SPECCODE NE 'ATBR' AND
           SPECCODE NE 'ATPU' AND SPECCODE NE 'AUSH' AND
           SPECCODE NE 'BBPL' AND SPECCODE NE 'BCPE' AND
           SPECCODE NE 'BHGU' AND SPECCODE NE 'BLGU' AND
           SPECCODE NE 'BLKI' AND SPECCODE NE 'BLSC' AND
           SPECCODE NE 'BLTE' AND SPECCODE NE 'DCCO' AND
           SPECCODE NE 'BOGU' AND SPECCODE NE 'DOVE' AND
           SPECCODE NE 'BRNO' AND SPECCODE NE 'DOWI' AND
           SPECCODE NE 'BRPE' AND SPECCODE NE 'FOTE' AND
           SPECCODE NE 'BRTE' AND SPECCODE NE 'GBBG' AND
           SPECCODE NE 'BSTP' AND SPECCODE NE 'GLGU' AND
           SPECCODE NE 'BUFF' AND SPECCODE NE 'GRCO' AND
           SPECCODE NE 'CAGO' AND SPECCODE NE 'GRSC' AND
           SPECCODE NE 'CATE' AND SPECCODE NE 'GRSH' AND
           SPECCODE NE 'COEI' AND SPECCODE NE 'GRSK' AND
           SPECCODE NE 'COLO' AND SPECCODE NE 'HERG' AND
           SPECCODE NE 'COMU' AND SPECCODE NE 'HOGR' AND
           SPECCODE NE 'COSH' AND SPECCODE NE 'ICGU' AND
           SPECCODE NE 'COTE' AND SPECCODE NE 'LAGU' AND
           SPECCODE NE 'LBBG' AND SPECCODE NE 'RAZO' AND
           SPECCODE NE 'LESP' AND SPECCODE NE 'RBGU' AND
           SPECCODE NE 'LETE' AND SPECCODE NE 'RBME' AND
           SPECCODE NE 'LIGU' AND SPECCODE NE 'RBTR' AND
           SPECCODE NE 'LTDU' AND SPECCODE NE 'REKN' AND
           SPECCODE NE 'LTJA' AND SPECCODE NE 'REPH' AND
           SPECCODE NE 'MABO' AND SPECCODE NE 'RNPH' AND
           SPECCODE NE 'MAGW' AND SPECCODE NE 'ROST' AND
           SPECCODE NE 'MALL' AND SPECCODE NE 'ROYT' AND
           SPECCODE NE 'MASH' AND SPECCODE NE 'RTLO' AND
           SPECCODE NE 'NOFU' AND SPECCODE NE 'RUTS' AND
           SPECCODE NE 'NOGA' AND SPECCODE NE 'SAGU' AND
           SPECCODE NE 'PAJA' AND SPECCODE NE 'SATE' AND
           SPECCODE NE 'PEEP' AND SPECCODE NE 'SOSH' AND
           SPECCODE NE 'POJA' AND SPECCODE NE 'SOTE' AND
           SPECCODE NE 'SPPL' AND SPECCODE NE 'UNCO' AND
           SPECCODE NE 'SPSK' AND SPECCODE NE 'UNCT' AND
           SPECCODE NE 'SUSC' AND SPECCODE NE 'UNDU' AND
           SPECCODE NE 'TBMU' AND SPECCODE NE 'UNGO' AND
           SPECCODE NE 'UNAL' AND SPECCODE NE 'UNGU' AND
           SPECCODE NE 'UNJA' AND SPECCODE NE 'UNLA' AND
           SPECCODE NE 'UNLG' AND SPECCODE NE 'UNLO' AND
           SPECCODE NE 'UNLS' AND SPECCODE NE 'UNME' AND
           SPECCODE NE 'UNMU' AND SPECCODE NE 'UNPH' AND
           SPECCODE NE 'UNSA' AND SPECCODE NE 'UNSC' AND
           SPECCODE NE 'UNSK' AND SPECCODE NE 'UNSP' AND
           SPECCODE NE 'UNSS' AND SPECCODE NE 'UNSU' AND
           SPECCODE NE 'UNSW' AND SPECCODE NE 'UNTE' AND
           SPECCODE NE 'WFSP' AND SPECCODE NE 'WHIM' AND
           SPECCODE NE 'WISP' AND SPECCODE NE 'WTTR' AND
           SPECCODE NE 'WWSC' AND SPECCODE NE 'BOWH' AND
           SPECCODE NE 'DUSH' AND SPECCODE NE 'SRWH' AND 
           SPECCODE NE 'EXPL' AND SPECCODE NE 'FG-A' AND
           SPECCODE NE 'SDOG' AND SPECCODE NE 'THSH' AND
           SPECCODE NE 'BESE' AND SPECCODE NE 'CG-S' AND 
           SPECCODE NE 'LFMS' AND SPECCODE NE 'SFMS' AND
           SPECCODE NE 'MKSH' AND SPECCODE NE 'RISE' AND
           SPECCODE NE 'TISH') THEN DO;
           FLAG = 'UNKNOWN SPECIES CODE';
           BADVALUE = SPECCODE;
           OUTPUT;
           END;
        IF TAXCODE = . THEN DO;
           FLAG = 'MISSING TAXON CODE';
           OUTPUT;
           END;
